### ISSUE TITLE
Improve seekTo prop to compare with future props rather then setting to null

### ISSUE THREAD

**Issue by xhluca** [plotly/dash-player#2]
Initial Comment: https://github.com/xhlulu/dash-player/pull/1#discussion_r206747946

TL;DR We should find a more elegant solution to verify if a new seekTo call is different from a previous one, rather than setting it to null.

We will keep this issue up until this component is released. If this becomes closed, feel free to reopen if the current solution poses problem. Also feel free to reopen

**Comment by alexshoe** [comment]
Using the current method for `seekTo` - this issue may be re-opened if related issues arise.
