### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by gaojingqi23** [plotly/dash-player#31]
what's the difference with DashPlayer that used by many videosites?
and why so few stars?

**Comment by alexshoe** [comment]
@gaojingqi23 ReactPlayer is a React media player that can play URLs "including file paths, YouTube, Facebook, Twitch, SoundCloud, Streamable...". Dash Player is a [Dash](https://github.com/plotly/dash) component that wraps ReactPlayer.

We are currently working towards bringing Dash Player to a production-ready version, which will then be made installable via `pip` as a formal versioned release.
