### ISSUE TITLE
dash-player/metadata.json not commited

### ISSUE THREAD

**Issue by Multihuntr** [plotly/dash-player#4]
Hey, found your dash component wrapper for this player and was interested in trying it out, but when trying to `import dash-player`, it says `No such file or directory: '/code/dash_player/metadata.json'`.

I admit to not knowing exactly how making a Dash component works, but I found [an issue on the base dash-core-components](https://github.com/plotly/dash-core-components/issues/31) which pointed me to the `.gitignore` file, and it seems that the `dash-player/metadata.json` file is not being tracked, but is required to run this player.

**Comment by Multihuntr** [comment]
Oh! Found [something else describing this problem and a solution](https://community.plot.ly/t/problem-with-writing-your-own-components/8230/2)

So, the solution is to add `npm prepublish` after `npm install`. I'll put in a pull request to modify the README.md with this additional step.

**Comment by alexshoe** [comment]
This[ this comment](https://github.com/plotly/dash-player/pull/5#issuecomment-1252613878)
